resource_types:

- name: sonar-runner
  type: docker-image
  source:
    repository: cathive/concourse-sonarqube-resource
    tag: latest # For reproducible builds use a specific tag and don't rely on "latest".
    
resources:
  - name: spring-boot-service
    type: git
    source:
      uri: https://github.com/gguptahcl/springboot-concourse-ci.git
      branch: master

  - name: code-analysis
    type: sonar-runner
    source:
      host_url: http://192.168.0.23:9000/
      login: ((sonarqube-login))
      password:  ((sonarqube-pwd))




jobs:
  - name: test
    public: true
    plan:
      - get: spring-boot-service
        trigger: true
      - task: mvn-test
        file: "spring-boot-service/concourse_ci/tasks/maven-test.yml"


  - name: sonar-scan
    public: true
    plan:
    - get: spring-boot-service
      passed:
        - test
      trigger: true
    - task: code-scan
      file: spring-boot-service/concourse_ci/tasks/sonarscan.yml