---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: alpine}

inputs:
  - name: spring-boot-service
  - login: ((sonarqube-login))

outputs:
  - name: sonar-scan-output

run:
  #path: spring-boot-service/concourse_ci/tasks/sonarscan.sh
  path: /bin/sh
  args: ["spring-boot-service/concourse_ci/tasks/sonarscan.sh"]
  
  