---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: spring-boot-service

outputs:
  - name: sonar-scan-output

run:
  path: spring-boot-service/concourse_ci/tasks/sonarscan.sh